export interface PlatformModuleSeed {
  code: string;
  name_en: string;
  name_ar: string;
  description_en: string;
  description_ar: string;
  /** RBAC page keys this module will gate later */
  page_keys: string[];
  sort_order: number;
  /** Single module value (OMR) */
  amount_omr: number;
  /** Default inclusion on seeded plans */
  in_plans: Array<'essential' | 'standard' | 'complete'>;
}

/** Product modules mapped to school system areas (pages linked later). */
export const PLATFORM_MODULE_SEED: PlatformModuleSeed[] = [
  {
    code: 'dashboard',
    name_en: 'Dashboard',
    name_ar: 'لوحة التحكم',
    description_en: 'School and mobile dashboards.',
    description_ar: 'لوحات التحكم للمدرسة والجوال.',
    page_keys: ['dashboard', 'mobile_dashboard'],
    sort_order: 1,
    amount_omr: 3,
    in_plans: ['essential', 'standard', 'complete'],
  },
  {
    code: 'users_roles',
    name_en: 'Users & roles',
    name_ar: 'المستخدمون والأدوار',
    description_en: 'Staff accounts and permission groups.',
    description_ar: 'حسابات الموظفين ومجموعات الصلاحيات.',
    page_keys: ['users', 'user_groups'],
    sort_order: 2,
    amount_omr: 5,
    in_plans: ['essential', 'standard', 'complete'],
  },
  {
    code: 'students',
    name_en: 'Students',
    name_ar: 'الطلاب',
    description_en: 'Student roster and registration.',
    description_ar: 'قائمة الطلاب والتسجيل.',
    page_keys: ['students', 'student_register'],
    sort_order: 3,
    amount_omr: 8,
    in_plans: ['essential', 'standard', 'complete'],
  },
  {
    code: 'class_groups',
    name_en: 'Class groups',
    name_ar: 'مجموعات الصفوف',
    description_en: 'Class / group management.',
    description_ar: 'إدارة المجموعات والصفوف.',
    page_keys: ['groups'],
    sort_order: 4,
    amount_omr: 4,
    in_plans: ['essential', 'standard', 'complete'],
  },
  {
    code: 'attendance',
    name_en: 'Attendance',
    name_ar: 'الحضور',
    description_en: 'Daily and session attendance.',
    description_ar: 'الحضور اليومي وحضور الجلسات.',
    page_keys: ['attendance', 'attendance_sessions'],
    sort_order: 5,
    amount_omr: 6,
    in_plans: ['essential', 'standard', 'complete'],
  },
  {
    code: 'schedules',
    name_en: 'Schedules',
    name_ar: 'الجداول',
    description_en: 'Class and teacher schedules.',
    description_ar: 'جداول الصفوف والمعلمين.',
    page_keys: ['schedules', 'teacher_schedule'],
    sort_order: 6,
    amount_omr: 5,
    in_plans: ['essential', 'standard', 'complete'],
  },
  {
    code: 'parent_portal',
    name_en: 'Parent portal',
    name_ar: 'بوابة أولياء الأمور',
    description_en: 'Parent dashboard, schedule, attendance, progress, activities.',
    description_ar: 'لوحة ولي الأمر والجداول والحضور والتقدم والأنشطة.',
    page_keys: [
      'parent_dashboard',
      'parent_schedule',
      'parent_attendance',
      'parent_progress',
      'parent_activities',
    ],
    sort_order: 7,
    amount_omr: 8,
    in_plans: ['essential', 'standard', 'complete'],
  },
  {
    code: 'school_settings',
    name_en: 'School settings',
    name_ar: 'إعدادات المدرسة',
    description_en: 'School settings and landing page.',
    description_ar: 'إعدادات المدرسة وصفحة الهبوط.',
    page_keys: ['settings'],
    sort_order: 8,
    amount_omr: 3,
    in_plans: ['essential', 'standard', 'complete'],
  },
  {
    code: 'messaging',
    name_en: 'Messaging & chat',
    name_ar: 'الرسائل والمحادثة',
    description_en: 'Group chat, direct messages, and formal letters.',
    description_ar: 'محادثة المجموعة والرسائل المباشرة والرسائل الرسمية.',
    page_keys: ['chat', 'messages', 'message_letters'],
    sort_order: 9,
    amount_omr: 7,
    in_plans: ['standard', 'complete'],
  },
  {
    code: 'notifications',
    name_en: 'Notifications',
    name_ar: 'الإشعارات',
    description_en: 'Notification templates.',
    description_ar: 'قوالب الإشعارات.',
    page_keys: ['notification_templates'],
    sort_order: 10,
    amount_omr: 3,
    in_plans: ['standard', 'complete'],
  },
  {
    code: 'courses',
    name_en: 'Courses',
    name_ar: 'المقررات',
    description_en: 'Courses and course enrollments.',
    description_ar: 'المقررات وتسجيل المقررات.',
    page_keys: ['courses', 'course_enrollments'],
    sort_order: 11,
    amount_omr: 7,
    in_plans: ['standard', 'complete'],
  },
  {
    code: 'graded_courses',
    name_en: 'Graded courses',
    name_ar: 'مقررات التقييم',
    description_en: 'Graded schemes, tasks, and marks.',
    description_ar: 'مخططات التقييم والمهام والدرجات.',
    page_keys: ['graded_courses', 'teacher_graded_tasks', 'teacher_graded_marks'],
    sort_order: 12,
    amount_omr: 9,
    in_plans: ['standard', 'complete'],
  },
  {
    code: 'progress',
    name_en: 'Progress tracking',
    name_ar: 'تتبع التقدم',
    description_en: 'Student progress tracking.',
    description_ar: 'تتبع تقدم الطلاب.',
    page_keys: ['progress'],
    sort_order: 13,
    amount_omr: 4,
    in_plans: ['standard', 'complete'],
  },
  {
    code: 'activities',
    name_en: 'Activities & approvals',
    name_ar: 'الأنشطة والموافقات',
    description_en: 'Activities workflow and approvals.',
    description_ar: 'مسار الأنشطة والموافقات.',
    page_keys: ['activities', 'approvals'],
    sort_order: 14,
    amount_omr: 5,
    in_plans: ['standard', 'complete'],
  },
  {
    code: 'reports',
    name_en: 'Reports',
    name_ar: 'التقارير',
    description_en: 'Operational reports and export.',
    description_ar: 'التقارير التشغيلية والتصدير.',
    page_keys: ['reports'],
    sort_order: 15,
    amount_omr: 4,
    in_plans: ['standard', 'complete'],
  },
  {
    code: 'transportation',
    name_en: 'Transportation',
    name_ar: 'النقل المدرسي',
    description_en: 'Buses and daily bus log.',
    description_ar: 'الحافلات وسجل الحافلات اليومي.',
    page_keys: ['transportation', 'transportation_daily_log'],
    sort_order: 16,
    amount_omr: 10,
    in_plans: ['standard', 'complete'],
  },
  {
    code: 'student_fees',
    name_en: 'Student fees',
    name_ar: 'رسوم الطلاب',
    description_en: 'Student payments and fee configuration.',
    description_ar: 'مدفوعات الطلاب وإعداد الرسوم.',
    page_keys: [
      'student_payments',
      'payment_levels',
      'payment_courses',
      'payment_packages',
      'payment_catalog_charges',
      'payment_catalog_discounts',
      'parent_fees',
    ],
    sort_order: 17,
    amount_omr: 10,
    in_plans: ['standard', 'complete'],
  },
  {
    code: 'enrollments',
    name_en: 'Enrollment applications',
    name_ar: 'طلبات التسجيل',
    description_en: 'Public enrollment applications workflow.',
    description_ar: 'مسار طلبات التسجيل العامة.',
    page_keys: ['enrollments'],
    sort_order: 18,
    amount_omr: 6,
    in_plans: ['complete'],
  },
  {
    code: 'meeting_rooms',
    name_en: 'Video meeting rooms',
    name_ar: 'غرف الاجتماعات',
    description_en: 'Admin and personal meeting rooms.',
    description_ar: 'غرف الاجتماعات الإدارية والشخصية.',
    page_keys: ['admin_meeting_rooms', 'my_meeting_rooms'],
    sort_order: 19,
    amount_omr: 12,
    in_plans: ['complete'],
  },
  {
    code: 'weekly_plans',
    name_en: 'Weekly session plans',
    name_ar: 'خطط الجلسات الأسبوعية',
    description_en: 'Weekly plans and teacher weekly sessions.',
    description_ar: 'الخطط الأسبوعية وجلسات المعلم.',
    page_keys: ['weekly_session_plans', 'teacher_weekly_sessions'],
    sort_order: 20,
    amount_omr: 5,
    in_plans: ['complete'],
  },
  {
    code: 'system_settings',
    name_en: 'System settings',
    name_ar: 'إعدادات النظام',
    description_en: 'Years, grades, and system configuration.',
    description_ar: 'السنوات والصفوف وإعدادات النظام.',
    page_keys: ['system_settings'],
    sort_order: 21,
    amount_omr: 3,
    in_plans: ['complete'],
  },
];
