import { groupKeyForSlug } from '@/docs/catalog'
import { demoAddressBar, withDemoQuery } from '@/utils/demo-play'
import {
  DEMO_AREA,
  DEMO_EMERGENCY_NAME,
  DEMO_EMERGENCY_RELATION,
  DEMO_CHILD_FIRST_AR,
  DEMO_CHILD_FIRST_EN,
  DEMO_CHILD_LAST_AR,
  DEMO_CHILD_LAST_EN,
  DEMO_CIVIL_ID,
  DEMO_DOB,
  DEMO_GUARDIAN_FIRST_AR,
  DEMO_GUARDIAN_FIRST_EN,
  DEMO_GUARDIAN_LAST_AR,
  DEMO_GUARDIAN_LAST_EN,
  DEMO_MOBILE,
  DEMO_NATIONALITY,
  DEMO_SCHOOL_SLUG,
  DEMO_VILLAGE,
} from '../defaults'
import { demoSay, type DemoAudience, type DemoStep, type DemoTopic } from '../types'

export function pageWalk(extra: DemoStep[] = []): DemoStep[] {
  return [
    { action: 'wait', ms: 500 },
    { action: 'waitFor', target: '[data-demo="page"], main, h1', ms: 8000 },
    demoSay('demo.say.page'),
    { action: 'move', target: '.fk-page-header h1, [data-demo="page"] h1, h1' },
    { action: 'wait', ms: 350 },
    demoSay('demo.say.filter'),
    { action: 'scroll', target: '[data-demo="filter"], select.fk-field, #group-select' },
    { action: 'move', target: '[data-demo="filter"], select.fk-field, #group-select' },
    { action: 'wait', ms: 280 },
    demoSay('demo.say.primary'),
    { action: 'scroll', target: '[data-demo="primary"], a.fk-btn--primary, .fk-btn--primary' },
    { action: 'move', target: '[data-demo="primary"], a.fk-btn--primary, .fk-btn--primary' },
    { action: 'wait', ms: 280 },
    demoSay('demo.say.row'),
    { action: 'scroll', target: '[data-demo="row"], tbody tr' },
    { action: 'move', target: '[data-demo="row"], tbody tr' },
    { action: 'wait', ms: 800 },
    ...extra,
  ]
}

function typeField(target: string, text: string): DemoStep[] {
  return [
    { action: 'scroll', target },
    { action: 'move', target },
    { action: 'type', target, text },
    { action: 'wait', ms: 160 },
  ]
}

function clickTarget(target: string): DemoStep[] {
  return [
    { action: 'scroll', target },
    { action: 'move', target },
    { action: 'wait', ms: 200 },
    { action: 'click', target },
    { action: 'wait', ms: 450 },
  ]
}

function clickNext(): DemoStep[] {
  return [
    { action: 'waitFor', target: '[data-demo="next"]:not([disabled])', ms: 8000 },
    ...clickTarget('[data-demo="next"]:not([disabled])'),
  ]
}

function studentDetailsFlow(): DemoStep[] {
  return [
    { action: 'waitFor', target: '[data-demo="first-name-ar"]', ms: 10000 },
    ...typeField('[data-demo="first-name-ar"]', DEMO_CHILD_FIRST_AR),
    ...typeField('[data-demo="first-name-en"]', DEMO_CHILD_FIRST_EN),
    ...typeField('[data-demo="last-name-ar"]', DEMO_CHILD_LAST_AR),
    ...typeField('[data-demo="last-name-en"]', DEMO_CHILD_LAST_EN),
    ...typeField('[data-demo="id-number"]', DEMO_CIVIL_ID),
    ...clickTarget('[data-demo="gender-male"]'),
    ...typeField('[data-demo="nationality"]', DEMO_NATIONALITY),
    ...typeField('[data-demo="dob"]', DEMO_DOB),
    ...clickNext(),
  ]
}

const registerStudentSteps: DemoStep[] = [
  { action: 'wait', ms: 400 },
  demoSay('demo.say.registerStudent'),
  ...studentDetailsFlow(),
  { action: 'waitFor', target: '[data-demo="grade"]', ms: 8000 },
  { action: 'waitFor', target: '[data-demo="grade"] option:not([value=""])', ms: 8000 },
  demoSay('demo.say.registerAcademic'),
  ...clickTarget('[data-demo="enroll-new"]'),
  { action: 'scroll', target: '[data-demo="grade"]' },
  { action: 'move', target: '[data-demo="grade"]' },
  { action: 'select', target: '[data-demo="grade"]' },
  { action: 'wait', ms: 350 },
  ...clickNext(),
  demoSay('demo.say.registerHealth'),
  { action: 'waitFor', target: '[data-demo="next"]', ms: 8000 },
  { action: 'wait', ms: 400 },
  ...clickNext(),
  { action: 'waitFor', target: '[data-demo="guardian-first-ar"]', ms: 8000 },
  demoSay('demo.say.registerGuardian'),
  ...typeField('[data-demo="guardian-first-ar"]', DEMO_GUARDIAN_FIRST_AR),
  ...typeField('[data-demo="guardian-first-en"]', DEMO_GUARDIAN_FIRST_EN),
  ...typeField('[data-demo="guardian-last-ar"]', DEMO_GUARDIAN_LAST_AR),
  ...typeField('[data-demo="guardian-last-en"]', DEMO_GUARDIAN_LAST_EN),
  ...typeField('[data-demo="guardian-mobile"]', DEMO_MOBILE),
  ...typeField('[data-demo="emergency-name"]', DEMO_EMERGENCY_NAME),
  ...typeField('[data-demo="emergency-mobile"]', DEMO_MOBILE),
  ...typeField('[data-demo="emergency-relation"]', DEMO_EMERGENCY_RELATION),
  ...clickNext(),
  { action: 'waitFor', target: '[data-demo="area"]', ms: 8000 },
  demoSay('demo.say.registerAddress'),
  ...typeField('[data-demo="area"]', DEMO_AREA),
  ...typeField('[data-demo="village"]', DEMO_VILLAGE),
  ...clickTarget('[data-demo="housing-house"]'),
  ...clickNext(),
  { action: 'waitFor', target: '[data-demo="group"], [data-demo="next"]', ms: 8000 },
  demoSay('demo.say.registerGroup'),
  ...clickTarget('[data-demo="group"]'),
  demoSay('demo.say.registerStop'),
  { action: 'scroll', target: '[data-demo="next"]' },
  { action: 'move', target: '[data-demo="next"]' },
  { action: 'wait', ms: 1200 },
]

function pageTopic(
  slug: string,
  audience: DemoAudience,
  path: string,
  steps?: DemoStep[],
): DemoTopic {
  return {
    slug,
    audience,
    groupKey: groupKeyForSlug(audience, slug) || (audience === 'parents' ? 'parentGettingStarted' : 'staffGettingStarted'),
    src: withDemoQuery(path, audience),
    addressBar: demoAddressBar(path),
    steps: steps || pageWalk(),
  }
}

export const pageDemos: DemoTopic[] = [
  pageTopic('school-settings', 'staff', '/settings', [
    ...pageWalk(),
    demoSay('demo.say.settingsGrades'),
    { action: 'navigate', path: '/settings/grades' },
    ...pageWalk(),
  ]),
  pageTopic('users-and-roles', 'staff', '/roles', [
    ...pageWalk(),
    demoSay('demo.say.usersEmployees'),
    { action: 'navigate', path: '/employees' },
    ...pageWalk(),
  ]),
  pageTopic('register-student', 'staff', '/students/register', registerStudentSteps),
  pageTopic('edit-student', 'staff', '/students', [
    ...pageWalk(),
    demoSay('demo.say.editRow'),
    ...clickTarget('[data-demo="row"]'),
    { action: 'wait', ms: 700 },
  ]),
  pageTopic('enrollment-inbox', 'staff', '/enrollments'),
  pageTopic('course-enrollments', 'staff', '/course-enrollments'),
  pageTopic('fixed-schedule', 'staff', '/schedules'),
  pageTopic('flexible-schedule', 'staff', '/flexible'),
  pageTopic('daily-attendance', 'staff', '/attendance', [
    { action: 'wait', ms: 400 },
    { action: 'waitFor', target: '[data-demo="group"]', ms: 10000 },
    demoSay('demo.say.attendanceGroup'),
    { action: 'move', target: '[data-demo="group"]' },
    { action: 'select', target: '[data-demo="group"]' },
    { action: 'wait', ms: 600 },
    demoSay('demo.say.attendanceDate'),
    { action: 'move', target: '[data-demo="date"]' },
    { action: 'wait', ms: 400 },
    demoSay('demo.say.attendanceRows'),
    { action: 'scroll', target: 'tbody tr, [data-demo="page"]' },
    { action: 'move', target: 'tbody tr' },
    { action: 'wait', ms: 900 },
  ]),
  pageTopic('session-attendance', 'staff', '/attendance/sessions'),
  pageTopic('activities', 'staff', '/activities'),
  pageTopic('milestone-courses', 'staff', '/courses'),
  pageTopic('graded-courses', 'staff', '/graded-courses'),
  pageTopic('standalone-courses', 'staff', '/standalone-courses'),
  pageTopic('materials-weekly-plans', 'staff', '/course-materials', [
    ...pageWalk(),
    demoSay('demo.say.materialsPlans'),
    { action: 'navigate', path: '/weekly-session-plans' },
    ...pageWalk(),
  ]),
  pageTopic('progress-marks', 'staff', '/progress', [
    ...pageWalk(),
    demoSay('demo.say.progressMarks'),
    { action: 'navigate', path: '/graded-marks' },
    ...pageWalk(),
  ]),
  pageTopic('catalogs-packages', 'staff', '/settings/payments/packages'),
  pageTopic('installment-plans', 'staff', '/settings/payments/installment-plans'),
  pageTopic('charge-sheets', 'staff', '/students/payments'),
  pageTopic('receipts-transfers', 'staff', '/students/payments/pending-receipts'),
  pageTopic('group-chat', 'staff', '/chat'),
  pageTopic('direct-messages', 'staff', '/messages'),
  pageTopic('meetings-live-class', 'staff', '/admin/meeting-rooms', [
    ...pageWalk(),
    demoSay('demo.say.meetingsRooms'),
    { action: 'navigate', path: '/my-meeting-rooms' },
    ...pageWalk(),
  ]),
  pageTopic('letters-templates', 'staff', '/settings/message-letters', [
    ...pageWalk(),
    demoSay('demo.say.lettersTemplates'),
    { action: 'navigate', path: '/settings/notification-templates' },
    ...pageWalk(),
  ]),
  pageTopic('fleet-assignment', 'staff', '/transportation'),
  pageTopic('daily-log', 'staff', '/transportation/daily-log'),
  pageTopic('academic-reports', 'staff', '/reports/academic'),
  pageTopic('financial-reports', 'staff', '/reports/financial'),
  pageTopic('landing-editor', 'staff', '/settings/landing-page'),
  pageTopic('public-enrollment', 'staff', `/s/${DEMO_SCHOOL_SLUG}`, [
    { action: 'wait', ms: 500 },
    { action: 'waitFor', target: '[data-demo="enroll"]', ms: 8000 },
    demoSay('demo.say.publicEnroll'),
    ...clickTarget('[data-demo="enroll"]'),
    demoSay('demo.say.publicStudent'),
    ...studentDetailsFlow(),
    { action: 'wait', ms: 800 },
  ]),
  pageTopic('parent-dashboard', 'parents', '/parent/dashboard', [
    ...pageWalk(),
    demoSay('demo.say.parentStats'),
    { action: 'scroll', target: '.archive-stat' },
    { action: 'move', target: '.archive-stat' },
    { action: 'wait', ms: 400 },
    { action: 'move', target: '.archive-stat:nth-child(2)' },
    { action: 'wait', ms: 400 },
    demoSay('demo.say.parentRecord'),
    { action: 'scroll', target: '.archive-record' },
    { action: 'move', target: '.archive-record' },
    { action: 'wait', ms: 800 },
  ]),
  pageTopic('switching-children', 'parents', '/parent/dashboard', [
    { action: 'wait', ms: 500 },
    { action: 'waitFor', target: '.archive-stat, [data-demo="page"]', ms: 8000 },
    demoSay('demo.say.parentSwitch'),
    { action: 'move', target: '.archive-stat' },
    { action: 'wait', ms: 350 },
    { action: 'move', target: '.archive-stat:nth-child(2)' },
    { action: 'wait', ms: 350 },
    { action: 'move', target: '.archive-stat:nth-child(3)' },
    { action: 'wait', ms: 350 },
    demoSay('demo.say.parentRecord'),
    { action: 'scroll', target: '.archive-record' },
    { action: 'move', target: '.archive-record' },
    { action: 'wait', ms: 800 },
  ]),
  pageTopic('parent-schedule', 'parents', '/parent/schedule'),
  pageTopic('parent-attendance', 'parents', '/parent/attendance'),
  pageTopic('parent-progress', 'parents', '/parent/progress'),
  pageTopic('parent-course-enrollments', 'parents', '/parent/course-enrollments'),
  pageTopic('parent-materials', 'parents', '/parent/course-materials'),
  pageTopic('parent-weekly-plans', 'parents', '/parent/weekly-plans'),
  pageTopic('parent-activities', 'parents', '/parent/assigned-activities'),
  pageTopic('parent-fees', 'parents', '/parent/fees', [
    ...pageWalk(),
    demoSay('demo.say.parentPay'),
    { action: 'scroll', target: '.fk-btn--primary, button' },
    { action: 'move', target: '.fk-btn--primary' },
    { action: 'wait', ms: 800 },
  ]),
  pageTopic('parent-pay', 'parents', '/parent/fees', [
    ...pageWalk(),
    demoSay('demo.say.parentPay'),
    { action: 'scroll', target: '.fk-btn--primary, button' },
    { action: 'move', target: '.fk-btn--primary' },
    { action: 'wait', ms: 800 },
  ]),
  pageTopic('parent-chats-meetings', 'parents', '/chat', [
    ...pageWalk(),
    demoSay('demo.say.parentChat'),
    { action: 'navigate', path: '/messages' },
    demoSay('demo.say.parentMessages'),
    ...pageWalk(),
    demoSay('demo.say.parentMeetings'),
    { action: 'navigate', path: '/my-meeting-rooms' },
    ...pageWalk(),
  ]),
  pageTopic('parent-bus', 'parents', '/parent/dashboard', [
    ...pageWalk(),
    demoSay('demo.say.parentRecord'),
    { action: 'scroll', target: '.archive-record' },
    { action: 'move', target: '.archive-record' },
    { action: 'wait', ms: 800 },
  ]),
]
