/** Business action for each controller method. Override with @BizLog on the handler. */
export const BIZ_LOG_CATALOG: Record<string, string> = {
  "AcademicYearController.archive": "start updating archive (academic years)",
  "AcademicYearController.create": "start creating academic years",
  "AcademicYearController.findActive": "start active academic years",
  "AcademicYearController.findAll": "start listing academic years",
  "AcademicYearController.findOne": "start fetching one of academic years",
  "AcademicYearController.getStatistics": "start fetching statistics (academic years)",
  "AcademicYearController.remove": "start deleting academic years",
  "AcademicYearController.setActive": "start updating set active (academic years)",
  "AcademicYearController.update": "start updating academic years",
  "ActivityController.create": "start creating activities",
  "ActivityController.findAll": "start listing activities",
  "ActivityController.findOne": "start fetching one of activities",
  "ActivityController.remove": "start deleting activities",
  "ActivityController.update": "start updating activities",
  "ActivityLogController.list": "start listing activity logs",
  "ActivityLogController.methods": "start fetching methods (activity logs)",
  "AttendanceController.bulkCreate": "start taking attendance for the class",
  "AttendanceController.checkExisting": "start checking if attendance already exists",
  "AttendanceController.create": "start taking attendance",
  "AttendanceController.findAll": "start fetching attendance records",
  "AttendanceController.findByDate": "start fetching attendance for a date",
  "AttendanceController.findByGroup": "start fetching class attendance",
  "AttendanceController.findByStudent": "start fetching student attendance",
  "AttendanceController.findOne": "start fetching one attendance record",
  "AttendanceController.getDailyReport": "start fetching the daily attendance report",
  "AttendanceController.getGroupStatistics": "start fetching class attendance statistics",
  "AttendanceController.getStudentStatistics": "start fetching student attendance statistics",
  "AttendanceController.remove": "start deleting an attendance record",
  "AttendanceController.update": "start updating an attendance record",
  "AuthController.changePassword": "start changing the password",
  "AuthController.deactivate": "start deactivating the session",
  "AuthController.getProfile": "start fetching the signed-in profile",
  "AuthController.listSchools": "start fetching schools for this account",
  "AuthController.login": "start signing in",
  "AuthController.refresh": "start refreshing the session",
  "AuthController.register": "start creating a user account",
  "AuthController.resetPassword": "start resetting the password",
  "AuthController.confirmResetPassword": "start confirming a password reset link",
  "AuthController.switchSchool": "start switching school",
  "AuthController.verify": "start verifying the session",
  "BusController.create": "start creating buses",
  "BusController.findAll": "start listing buses",
  "BusController.findOne": "start fetching one of buses",
  "BusController.listMovements": "start fetching movements (buses)",
  "BusController.listStudentsOnBus": "start fetching students on bus (buses)",
  "BusController.logMovement": "start log movement (buses)",
  "BusController.logMovementsBulk": "start log movements bulk (buses)",
  "BusController.remove": "start deleting buses",
  "BusController.setStudentPickup": "start updating set student pickup (buses)",
  "BusController.getEta": "start fetching bus stop ETAs",
  "BusController.update": "start updating buses",
  "BusController.updatePosition": "start updating update position (buses)",
  "ChatController.adminReviewMessages": "start fetching reviewed messages (chat)",
  "ChatController.adminReviewNotice": "start fetching chat review notice (chat)",
  "ChatController.adminReviewSearch": "start searching reviewed conversations (chat)",
  "ChatController.approvalInbox": "start fetching approval inbox (chat)",
  "ChatController.createFromBus": "start creating chat",
  "ChatController.createRoom": "start creating chat",
  "ChatController.directMessages": "start fetching direct messages (chat)",
  "ChatController.directThreadPeer": "start fetching direct thread peer (chat)",
  "ChatController.listDirectThreads": "start fetching direct threads (chat)",
  "ChatController.listGroups": "start fetching groups (chat)",
  "ChatController.markRead": "start mark read (chat)",
  "ChatController.memberCandidates": "start fetching member candidates (chat)",
  "ChatController.messages": "start fetching messages (chat)",
  "ChatController.openDirect": "start open direct (chat)",
  "ChatController.openFromCourse": "start open from course (chat)",
  "ChatController.parentContacts": "start fetching parent contacts (chat)",
  "ChatController.renderedLetter": "start fetching rendered letter (chat)",
  "ChatController.resolveMessageLetterApproval": "start updating resolve message letter approval (chat)",
  "ChatController.setMembers": "start updating set members (chat)",
  "ChatController.suggestedContacts": "start fetching suggested contacts (chat)",
  "ClassSettingsController.addDuration": "start add duration (class settings)",
  "ClassSettingsController.addStartTime": "start add start time (class settings)",
  "ClassSettingsController.create": "start creating class settings",
  "ClassSettingsController.findActive": "start active class settings",
  "ClassSettingsController.findAll": "start listing class settings",
  "ClassSettingsController.findOne": "start fetching one of class settings",
  "ClassSettingsController.getAvailableTimeSlots": "start fetching available time slots (class settings)",
  "ClassSettingsController.getOrCreateDefault": "start fetching or create default (class settings)",
  "ClassSettingsController.remove": "start deleting class settings",
  "ClassSettingsController.removeDuration": "start deleting remove duration (class settings)",
  "ClassSettingsController.removeStartTime": "start deleting remove start time (class settings)",
  "ClassSettingsController.setActive": "start updating set active (class settings)",
  "ClassSettingsController.setDefaultDuration": "start updating set default duration (class settings)",
  "ClassSettingsController.update": "start updating class settings",
  "ClassSettingsController.updateDuration": "start updating update duration (class settings)",
  "ClassSettingsController.validateTimeSlot": "start validate time slot (class settings)",
  "CourseController.create": "start creating courses",
  "CourseController.duplicate": "start duplicate (courses)",
  "CourseController.findActive": "start active courses",
  "CourseController.findAll": "start listing courses",
  "CourseController.findByAgeGroup": "start fetching by age group (courses)",
  "CourseController.findByStatus": "start fetching by status (courses)",
  "CourseController.findOne": "start fetching one of courses",
  "CourseController.getSchema": "start fetching schema (courses)",
  "CourseController.getStatistics": "start fetching statistics (courses)",
  "CourseController.remove": "start deleting courses",
  "CourseController.search": "start searching courses",
  "CourseController.update": "start updating courses",
  "CourseController.updateStatus": "start updating update status (courses)",
  "CourseMaterialController.board": "start fetching board (course materials)",
  "CourseMaterialController.createTopic": "start creating course materials",
  "CourseMaterialController.download": "start fetching download (course materials)",
  "CourseMaterialController.list": "start listing course materials",
  "CourseMaterialController.listCourses": "start fetching courses (course materials)",
  "CourseMaterialController.remove": "start deleting course materials",
  "CourseMaterialController.removeTopic": "start deleting remove topic (course materials)",
  "CourseMaterialController.update": "start updating course materials",
  "CourseMaterialController.updateTopic": "start updating update topic (course materials)",
  "CourseMaterialController.upload": "start upload (course materials)",
  "DebugController.executeQuery": "start execute query (debug)",
  "DebugController.getTableInfo": "start fetching table info (debug)",
  "DebugController.getTables": "start fetching tables (debug)",
  "DebugController.testDatabase": "start fetching test database (debug)",
  "EnrollmentController.approve": "start updating approve (an enrollment application)",
  "EnrollmentController.create": "start creating an enrollment application",
  "EnrollmentController.findAll": "start listing an enrollment application",
  "EnrollmentController.findOne": "start fetching one of an enrollment application",
  "EnrollmentController.generateDocument": "start fetching generate document (an enrollment application)",
  "EnrollmentController.reject": "start updating reject (an enrollment application)",
  "EnrollmentController.remove": "start deleting an enrollment application",
  "EnrollmentController.update": "start updating an enrollment application",
  "EnrollmentResponsibilityController.create": "start creating enrollment responsibilities",
  "EnrollmentResponsibilityController.list": "start listing enrollment responsibilities",
  "EnrollmentResponsibilityController.remove": "start deleting enrollment responsibilities",
  "EnrollmentResponsibilityController.update": "start updating enrollment responsibilities",
  "FeePackageController.create": "start creating fee packages",
  "FeePackageController.getOne": "start fetching one of fee packages",
  "FeePackageController.list": "start listing fee packages",
  "FeePackageController.remove": "start deleting fee packages",
  "FeePackageController.update": "start updating fee packages",
  "FeesV2Controller.approvePayment": "start approve payment (fees)",
  "FeesV2Controller.approveTransfer": "start approve transfer (fees)",
  "FeesV2Controller.assignPlan": "start updating assign plan (fees)",
  "FeesV2Controller.confirmThawani": "start confirm thawani (fees)",
  "FeesV2Controller.createPackage": "start creating fees",
  "FeesV2Controller.createPlan": "start creating fees",
  "FeesV2Controller.createThawaniSession": "start creating fees",
  "FeesV2Controller.createTransfer": "start creating fees",
  "FeesV2Controller.deletePackage": "start deleting delete package (fees)",
  "FeesV2Controller.deletePlan": "start deleting delete plan (fees)",
  "FeesV2Controller.dueInstallmentsReport": "start fetching due installments report (fees)",
  "FeesV2Controller.getBusLink": "start fetching bus link (fees)",
  "FeesV2Controller.getCourseLink": "start fetching course link (fees)",
  "FeesV2Controller.getGradeLink": "start fetching grade link (fees)",
  "FeesV2Controller.getPackage": "start fetching package (fees)",
  "FeesV2Controller.getPackageUsage": "start fetching package usage (fees)",
  "FeesV2Controller.getPlan": "start fetching plan (fees)",
  "FeesV2Controller.getPlanUsage": "start fetching plan usage (fees)",
  "FeesV2Controller.getStudentSheet": "start fetching student sheet (fees)",
  "FeesV2Controller.listChargeSheetSummaries": "start fetching charge sheet summaries (fees)",
  "FeesV2Controller.listGradeLinks": "start fetching grade links (fees)",
  "FeesV2Controller.listPackages": "start fetching packages (fees)",
  "FeesV2Controller.listPendingPayments": "start fetching pending payments (fees)",
  "FeesV2Controller.listPendingReconcile": "start fetching pending reconcile (fees)",
  "FeesV2Controller.listPlans": "start fetching plans (fees)",
  "FeesV2Controller.listStudentPayments": "start fetching student payments (fees)",
  "FeesV2Controller.listTransfers": "start fetching transfers (fees)",
  "FeesV2Controller.payInstallment": "start pay installment (fees)",
  "FeesV2Controller.payUpfront": "start pay upfront (fees)",
  "FeesV2Controller.refreshStudentSheet": "start refresh student sheet (fees)",
  "FeesV2Controller.rejectPayment": "start reject payment (fees)",
  "FeesV2Controller.rejectTransfer": "start reject transfer (fees)",
  "FeesV2Controller.setDiscounts": "start updating set discounts (fees)",
  "FeesV2Controller.submitOfflinePayment": "start submit offline payment (fees)",
  "FeesV2Controller.thawaniWebhook": "start thawani webhook (fees)",
  "FeesV2Controller.updatePackage": "start updating update package (fees)",
  "FeesV2Controller.updatePlan": "start updating update plan (fees)",
  "FeesV2Controller.upsertBusLink": "start updating upsert bus link (fees)",
  "FeesV2Controller.upsertCourseLink": "start updating upsert course link (fees)",
  "FeesV2Controller.upsertGradeLink": "start updating upsert grade link (fees)",
  "FileUploadController.getFile": "start fetching file (a file)",
  "FileUploadController.uploadDocument": "start upload document (a file)",
  "FileUploadController.uploadStaffPhoto": "start upload staff photo (a file)",
  "FileUploadController.uploadStudentPhoto": "start upload student photo (a file)",
  "GradeController.create": "start creating grade levels",
  "GradeController.findActive": "start active grade levels",
  "GradeController.findAll": "start listing grade levels",
  "GradeController.findOne": "start fetching one of grade levels",
  "GradeController.initializeDefaults": "start initialize defaults (grade levels)",
  "GradeController.remove": "start deleting grade levels",
  "GradeController.reorder": "start reorder (grade levels)",
  "GradeController.update": "start updating grade levels",
  "GradedAssessmentController.create": "start creating graded courses",
  "GradedAssessmentController.duplicate": "start duplicate (graded courses)",
  "GradedAssessmentController.findOne": "start fetching one of graded courses",
  "GradedAssessmentController.list": "start listing graded courses",
  "GradedAssessmentController.remove": "start deleting graded courses",
  "GradedAssessmentController.update": "start updating graded courses",
  "GradedCriterionMarksController.classReport": "start fetching class report (graded marks)",
  "GradedCriterionMarksController.grid": "start fetching grid (graded marks)",
  "GradedCriterionMarksController.saveGrid": "start save grid (graded marks)",
  "GradedCriterionMarksController.studentReport": "start fetching student report (graded marks)",
  "GradedCriterionTaskController.append": "start append (graded tasks)",
  "GradedCriterionTaskController.eligibleCourses": "start fetching eligible courses (graded tasks)",
  "GradedCriterionTaskController.marksGrid": "start fetching marks grid (graded tasks)",
  "GradedCriterionTaskController.patch": "start updating patch (graded tasks)",
  "GradedCriterionTaskController.remove": "start deleting graded tasks",
  "GradedCriterionTaskController.saveMarksGrid": "start save marks grid (graded tasks)",
  "GradedCriterionTaskController.summary": "start fetching summary (graded tasks)",
  "GradedCriterionTaskController.sync": "start sync (graded tasks)",
  "GroupController.create": "start creating classes",
  "GroupController.deactivate": "start updating deactivate (classes)",
  "GroupController.findAll": "start listing classes",
  "GroupController.findByAcademicYear": "start fetching by academic year (classes)",
  "GroupController.findBySupervisor": "start fetching by supervisor (classes)",
  "GroupController.findOne": "start fetching one of classes",
  "GroupController.getCapacity": "start fetching capacity (classes)",
  "GroupController.getStatistics": "start fetching statistics (classes)",
  "GroupController.remove": "start deleting classes",
  "GroupController.update": "start updating classes",
  "GroupController.updateStudentCount": "start updating update student count (classes)",
  "MailController.sendTest": "start send test (mail)",
  "MeetingRoomController.create": "start creating a meeting room",
  "MeetingRoomController.end": "start end (a meeting room)",
  "MeetingRoomController.getOne": "start fetching one of a meeting room",
  "MeetingRoomController.join": "start join (a meeting room)",
  "MeetingRoomController.list": "start listing a meeting room",
  "MeetingRoomController.mine": "start fetching mine (a meeting room)",
  "MeetingRoomController.update": "start updating a meeting room",
  "MessageLetterController.addFile": "start add file (letters)",
  "MessageLetterController.approvalRecipients": "start fetching approval recipients (letters)",
  "MessageLetterController.audiencePreview": "start audience preview (letters)",
  "MessageLetterController.create": "start creating letters",
  "MessageLetterController.dispatch": "start dispatch (letters)",
  "MessageLetterController.list": "start listing letters",
  "MessageLetterController.one": "start fetching one of letters",
  "MessageLetterController.remind": "start remind (letters)",
  "MessageLetterController.remove": "start deleting letters",
  "MessageLetterController.removeFile": "start deleting remove file (letters)",
  "MessageLetterController.sampleVariables": "start fetching sample variables (letters)",
  "MessageLetterController.update": "start updating letters",
  "MilestoneController.create": "start creating milestones",
  "MilestoneController.duplicate": "start duplicate (milestones)",
  "MilestoneController.findByCourse": "start fetching by course (milestones)",
  "MilestoneController.findByPhase": "start fetching by phase (milestones)",
  "MilestoneController.findOne": "start fetching one of milestones",
  "MilestoneController.getNextOrder": "start fetching next order (milestones)",
  "MilestoneController.getRequiredMilestones": "start fetching required milestones (milestones)",
  "MilestoneController.getStats": "start fetching stats (milestones)",
  "MilestoneController.remove": "start deleting milestones",
  "MilestoneController.reorderMilestones": "start updating reorder milestones (milestones)",
  "MilestoneController.update": "start updating milestones",
  "NotificationLayoutController.create": "start creating school email layouts",
  "NotificationLayoutController.list": "start listing school email layouts",
  "NotificationLayoutController.one": "start fetching one of school email layouts",
  "NotificationLayoutController.preview": "start preview (school email layouts)",
  "NotificationLayoutController.remove": "start deleting school email layouts",
  "NotificationLayoutController.update": "start updating school email layouts",
  "NotificationTemplateController.definitions": "start fetching definitions (notification templates)",
  "NotificationTemplateController.listForSchool": "start fetching for school (notification templates)",
  "NotificationTemplateController.one": "start fetching one of notification templates",
  "NotificationTemplateController.preview": "start preview (notification templates)",
  "NotificationTemplateController.reset": "start deleting reset (notification templates)",
  "NotificationTemplateController.sampleVariables": "start fetching sample variables (notification templates)",
  "NotificationTemplateController.upsert": "start updating upsert (notification templates)",
  "OnlineSessionController.attendance": "start fetching attendance (an online session)",
  "OnlineSessionController.attendanceRecords": "start fetching attendance records (an online session)",
  "OnlineSessionController.createOrGet": "start creating an online session",
  "OnlineSessionController.join": "start join (an online session)",
  "OnlineSessionController.presence": "start presence (an online session)",
  "OnlineSessionController.resolve": "start fetching resolve (an online session)",
  "OnlineSessionController.studentAttendance": "start fetching student attendance (an online session)",
  "OutboundMessageTransactionController.getOne": "start fetching one of outbound messages",
  "OutboundMessageTransactionController.list": "start listing outbound messages",
  "OutboundMessageTransactionController.resend": "start resend (outbound messages)",
  "ParentController.assignToStudent": "start linking a parent to a student",
  "ParentController.create": "start creating a parent",
  "ParentController.findAll": "start fetching parents",
  "ParentController.findOne": "start fetching parent details",
  "ParentController.getMyAssignedActivities": "start fetching parent activities",
  "ParentController.getMyAttendance": "start fetching parent attendance",
  "ParentController.getMyBusMovements": "start fetching parent bus movements",
  "ParentController.getMyBusPositions": "start fetching parent bus positions",
  "ParentController.getMyDashboardData": "start fetching parent dashboard data",
  "ParentController.getMyWeeklyPlans": "start fetching parent weekly plans",
  "ParentController.remove": "start deleting a parent",
  "ParentController.removeFromStudent": "start removing a parent from a student",
  "ParentController.resetPassword": "start resetting a parent password",
  "ParentController.search": "start searching parents",
  "ParentController.shareChildBusPickup": "start updating child bus pickup",
  "ParentController.unassignFromStudent": "start unlinking a parent from a student",
  "ParentController.update": "start updating a parent",
  "PaymentConfigController.coursesPaymentSummary": "start fetching courses payment summary (payment setup)",
  "PaymentConfigController.createChargeType": "start creating payment setup",
  "PaymentConfigController.createDiscountType": "start creating payment setup",
  "PaymentConfigController.createExtraType": "start creating payment setup",
  "PaymentConfigController.createInclusionType": "start creating payment setup",
  "PaymentConfigController.createLevel": "start creating payment setup",
  "PaymentConfigController.deleteChargeType": "start deleting delete charge type (payment setup)",
  "PaymentConfigController.deleteDiscountType": "start deleting delete discount type (payment setup)",
  "PaymentConfigController.deleteExtraType": "start deleting delete extra type (payment setup)",
  "PaymentConfigController.deleteInclusionType": "start deleting delete inclusion type (payment setup)",
  "PaymentConfigController.deleteLevel": "start deleting delete level (payment setup)",
  "PaymentConfigController.getCourseProfile": "start fetching course profile (payment setup)",
  "PaymentConfigController.getProfile": "start fetching profile (payment setup)",
  "PaymentConfigController.getSchoolFlags": "start fetching school flags (payment setup)",
  "PaymentConfigController.listChargeTypes": "start fetching charge types (payment setup)",
  "PaymentConfigController.listDiscountTypes": "start fetching discount types (payment setup)",
  "PaymentConfigController.listExtraTypes": "start fetching extra types (payment setup)",
  "PaymentConfigController.listInclusionTypes": "start fetching inclusion types (payment setup)",
  "PaymentConfigController.listLevels": "start fetching levels (payment setup)",
  "PaymentConfigController.listLevelsSummary": "start fetching levels summary (payment setup)",
  "PaymentConfigController.patchSchoolFlags": "start updating patch school flags (payment setup)",
  "PaymentConfigController.putCourseProfile": "start updating put course profile (payment setup)",
  "PaymentConfigController.putProfile": "start updating put profile (payment setup)",
  "PaymentConfigController.updateChargeType": "start updating update charge type (payment setup)",
  "PaymentConfigController.updateDiscountType": "start updating update discount type (payment setup)",
  "PaymentConfigController.updateExtraType": "start updating update extra type (payment setup)",
  "PaymentConfigController.updateInclusionType": "start updating update inclusion type (payment setup)",
  "PaymentConfigController.updateLevel": "start updating update level (payment setup)",
  "PhaseController.create": "start creating course phases",
  "PhaseController.duplicate": "start duplicate (course phases)",
  "PhaseController.findByCourse": "start fetching by course (course phases)",
  "PhaseController.findOne": "start fetching one of course phases",
  "PhaseController.getNextOrder": "start fetching next order (course phases)",
  "PhaseController.remove": "start deleting course phases",
  "PhaseController.reorderPhases": "start updating reorder phases (course phases)",
  "PhaseController.update": "start updating course phases",
  "PlatformBillingController.createPlan": "start creating platform billing",
  "PlatformBillingController.deletePlan": "start deleting delete plan (platform billing)",
  "PlatformBillingController.getCustomPlanRequest": "start fetching custom plan request (platform billing)",
  "PlatformBillingController.getPlan": "start fetching plan (platform billing)",
  "PlatformBillingController.getSubscription": "start fetching subscription (platform billing)",
  "PlatformBillingController.issueInvoice": "start issue invoice (platform billing)",
  "PlatformBillingController.listCustomPlanRequests": "start fetching custom plan requests (platform billing)",
  "PlatformBillingController.listModules": "start fetching modules (platform billing)",
  "PlatformBillingController.listPlans": "start fetching plans (platform billing)",
  "PlatformBillingController.listSchoolModules": "start fetching school modules (platform billing)",
  "PlatformBillingController.markPaid": "start mark paid (platform billing)",
  "PlatformBillingController.setSchoolModules": "start updating set school modules (platform billing)",
  "PlatformBillingController.updateCustomPlanRequest": "start updating update custom plan request (platform billing)",
  "PlatformBillingController.updateModule": "start updating update module (platform billing)",
  "PlatformBillingController.updatePlan": "start updating update plan (platform billing)",
  "PlatformBillingController.upsertSubscription": "start updating upsert subscription (platform billing)",
  "PlatformNotificationLayoutController.create": "start creating platform email layouts",
  "PlatformNotificationLayoutController.list": "start listing platform email layouts",
  "PlatformNotificationLayoutController.one": "start fetching one of platform email layouts",
  "PlatformNotificationLayoutController.preview": "start preview (platform email layouts)",
  "PlatformNotificationLayoutController.remove": "start deleting platform email layouts",
  "PlatformNotificationLayoutController.update": "start updating platform email layouts",
  "PlatformNotificationTemplateController.list": "start listing platform notification templates",
  "PlatformNotificationTemplateController.one": "start fetching one of platform notification templates",
  "PlatformNotificationTemplateController.preview": "start preview (platform notification templates)",
  "PlatformNotificationTemplateController.reset": "start deleting reset (platform notification templates)",
  "PlatformNotificationTemplateController.sampleVariables": "start fetching sample variables (platform notification templates)",
  "PlatformNotificationTemplateController.upsert": "start updating upsert (platform notification templates)",
  "PlatformSchoolController.approve": "start approve (platform schools)",
  "PlatformSchoolController.create": "start creating platform schools",
  "PlatformSchoolController.getOne": "start fetching one of platform schools",
  "PlatformSchoolController.list": "start listing platform schools",
  "PlatformSchoolController.reject": "start reject (platform schools)",
  "PlatformSchoolController.resendOwnerLogin": "start resend owner login (platform schools)",
  "PlatformSchoolController.update": "start updating platform schools",
  "PublicDemoController.session": "start session (a public demo session)",
  "PublicEnrollmentFeesController.plans": "start fetching plans (public enrollment fees)",
  "PublicEnrollmentFeesController.preview": "start fetching preview (public enrollment fees)",
  "PublicEnrollmentResponsibilitiesController.list": "start listing public enrollment responsibilities",
  "PublicLetterApprovalController.decide": "start decide (public letter approval)",
  "PublicLetterApprovalController.preview": "start fetching preview (public letter approval)",
  "PublicMessageLetterFileController.download": "start fetching download (a letter file)",
  "PublicPlatformPlansController.list": "start listing public plans",
  "PublicSchoolLandingController.getBySlug": "start fetching by slug (the public school landing)",
  "PublicSchoolLandingController.getDefault": "start fetching default (the public school landing)",
  "PublicSchoolLandingController.schoolById": "start fetching school by id (the public school landing)",
  "PublicSchoolLandingController.schoolBySlug": "start fetching school by slug (the public school landing)",
  "RbacController.addMember": "start add member (user-group permissions)",
  "RbacController.catalog": "start fetching catalog (user-group permissions)",
  "RbacController.cloneGroup": "start clone group (user-group permissions)",
  "RbacController.createGroup": "start creating user-group permissions",
  "RbacController.deleteGroup": "start deleting delete group (user-group permissions)",
  "RbacController.getGroup": "start fetching group (user-group permissions)",
  "RbacController.listGroups": "start fetching groups (user-group permissions)",
  "RbacController.listOverrides": "start fetching overrides (user-group permissions)",
  "RbacController.myClaims": "start fetching my claims (user-group permissions)",
  "RbacController.removeMember": "start deleting remove member (user-group permissions)",
  "RbacController.setOverrides": "start updating set overrides (user-group permissions)",
  "RbacController.setPermissions": "start updating set permissions (user-group permissions)",
  "RbacController.updateGroup": "start updating update group (user-group permissions)",
  "RbacController.userClaims": "start fetching user claims (user-group permissions)",
  "RbacController.userGroups": "start fetching user groups (user-group permissions)",
  "ScheduleAutoController.createDemand": "start creating auto schedule",
  "ScheduleAutoController.deleteDemand": "start deleting delete demand (auto schedule)",
  "ScheduleAutoController.generate": "start generate (auto schedule)",
  "ScheduleAutoController.listDemands": "start fetching demands (auto schedule)",
  "ScheduleAutoController.replaceDemands": "start replace demands (auto schedule)",
  "ScheduleAutoController.updateDemand": "start updating update demand (auto schedule)",
  "ScheduleController.cancel": "start updating cancel (the schedule)",
  "ScheduleController.create": "start creating the schedule",
  "ScheduleController.findAll": "start listing the schedule",
  "ScheduleController.findByDay": "start fetching by day (the schedule)",
  "ScheduleController.findByGroup": "start fetching by group (the schedule)",
  "ScheduleController.findByRoom": "start fetching by room (the schedule)",
  "ScheduleController.findByTeacher": "start fetching by teacher (the schedule)",
  "ScheduleController.findOne": "start fetching one of the schedule",
  "ScheduleController.findTeacherCourses": "start fetching teacher courses (the schedule)",
  "ScheduleController.getWeeklySchedule": "start fetching weekly schedule (the schedule)",
  "ScheduleController.remove": "start deleting the schedule",
  "ScheduleController.update": "start updating the schedule",
  "SchoolBillingController.confirmThawani": "start confirm thawani (school billing)",
  "SchoolBillingController.createThawaniSession": "start creating school billing",
  "SchoolBillingController.me": "start fetching me (school billing)",
  "SchoolLandingPageController.getMine": "start fetching mine (the school landing page)",
  "SchoolLandingPageController.upsert": "start updating upsert (the school landing page)",
  "SchoolSubscriptionController.register": "start register (school signup)",
  "SchoolSubscriptionController.sendEmailOtp": "start send email otp (school signup)",
  "SchoolSubscriptionController.submitCustomPlanRequest": "start submit custom plan request (school signup)",
  "SchoolSubscriptionController.submitInquiry": "start submit inquiry (school signup)",
  "SchoolSubscriptionController.verifyEmailOtp": "start verify email otp (school signup)",
  "SchoolSystemSettingController.bulk": "start bulk (school settings)",
  "SchoolSystemSettingController.create": "start creating school settings",
  "SchoolSystemSettingController.findAll": "start listing school settings",
  "SchoolSystemSettingController.findByCategory": "start fetching by category (school settings)",
  "SchoolSystemSettingController.findByKey": "start fetching by key (school settings)",
  "SchoolSystemSettingController.removeByKey": "start deleting remove by key (school settings)",
  "SchoolSystemSettingController.updateByKey": "start updating update by key (school settings)",
  "SemesterController.activate": "start updating activate (semesters)",
  "SemesterController.create": "start creating semesters",
  "SemesterController.findAll": "start listing semesters",
  "SemesterController.findByAcademicYear": "start fetching by academic year (semesters)",
  "SemesterController.findCurrentSemester": "start fetching current semester (semesters)",
  "SemesterController.findOne": "start fetching one of semesters",
  "SemesterController.getStatistics": "start fetching statistics (semesters)",
  "SemesterController.remove": "start deleting semesters",
  "SemesterController.update": "start updating semesters",
  "SemesterController.validateSemesterOrder": "start fetching validate semester order (semesters)",
  "SessionMediaController.deleteMedia": "start deleting delete media (session media)",
  "SessionMediaController.getMediaById": "start fetching media by id (session media)",
  "SessionMediaController.getMediaBySessionPlan": "start fetching media by session plan (session media)",
  "SessionMediaController.uploadFile": "start upload file (session media)",
  "SessionMediaController.uploadMultipleFiles": "start upload multiple files (session media)",
  "StatisticsController.getAttendanceStats": "start fetching attendance stats (statistics)",
  "StatisticsController.getCourseStats": "start fetching course stats (statistics)",
  "StatisticsController.getDashboardStats": "start fetching dashboard stats (statistics)",
  "StatisticsController.getStudentProgressStats": "start fetching student progress stats (statistics)",
  "StudentController.assignToBus": "start assigning a student to a bus",
  "StudentController.assignToGroup": "start assigning a student to a class",
  "StudentController.create": "start creating a student",
  "StudentController.findAll": "start fetching students",
  "StudentController.findByBus": "start fetching students on a bus",
  "StudentController.findByGroup": "start fetching students in a class",
  "StudentController.findByParent": "start fetching students for a parent",
  "StudentController.findOne": "start fetching student details",
  "StudentController.getProgress": "start fetching student progress",
  "StudentController.registerInApp": "start registering a student",
  "StudentController.remove": "start deleting a student",
  "StudentController.removeFromBus": "start removing a student from a bus",
  "StudentController.search": "start searching students",
  "StudentController.update": "start updating student details",
  "StudentCourseEnrollmentController.availableStudents": "start fetching available students (course enrollments)",
  "StudentCourseEnrollmentController.drop": "start deleting drop (course enrollments)",
  "StudentCourseEnrollmentController.enrollCourse": "start enroll course (course enrollments)",
  "StudentCourseEnrollmentController.enrollStudent": "start enroll student (course enrollments)",
  "StudentCourseEnrollmentController.enrollableCourses": "start fetching enrollable courses (course enrollments)",
  "StudentCourseEnrollmentController.list": "start listing course enrollments",
  "StudentPaymentController.addDiscount": "start add discount (student payments)",
  "StudentPaymentController.clearInstallment": "start deleting clear installment (student payments)",
  "StudentPaymentController.ensure": "start ensure (student payments)",
  "StudentPaymentController.getByStudent": "start fetching by student (student payments)",
  "StudentPaymentController.list": "start listing student payments",
  "StudentPaymentController.listByStudent": "start fetching by student (student payments)",
  "StudentPaymentController.listFeeCharges": "start fetching fee charges (student payments)",
  "StudentPaymentController.patchAdminTotal": "start updating patch admin total (student payments)",
  "StudentPaymentController.payInstallment": "start pay installment (student payments)",
  "StudentPaymentController.paymentHistory": "start fetching payment history (student payments)",
  "StudentPaymentController.previewPayment": "start preview payment (student payments)",
  "StudentPaymentController.recordPayment": "start record payment (student payments)",
  "StudentPaymentController.removeDiscount": "start deleting remove discount (student payments)",
  "StudentProgressController.bulkUpdate": "start bulk update (student progress)",
  "StudentProgressController.create": "start creating student progress",
  "StudentProgressController.findAll": "start listing student progress",
  "StudentProgressController.findByCourse": "start fetching by course (student progress)",
  "StudentProgressController.findByMilestone": "start fetching by milestone (student progress)",
  "StudentProgressController.findByStudent": "start fetching by student (student progress)",
  "StudentProgressController.findByStudentAndCourse": "start fetching by student and course (student progress)",
  "StudentProgressController.findByStudentAndMilestone": "start fetching by student and milestone (student progress)",
  "StudentProgressController.findOne": "start fetching one of student progress",
  "StudentProgressController.getCourseProgressSummary": "start fetching course progress summary (student progress)",
  "StudentProgressController.getMilestoneProgressSummary": "start fetching milestone progress summary (student progress)",
  "StudentProgressController.getStudentCourseProgress": "start fetching student course progress (student progress)",
  "StudentProgressController.remove": "start deleting student progress",
  "StudentProgressController.update": "start updating student progress",
  "UserController.create": "start creating staff users",
  "UserController.findAll": "start listing staff users",
  "UserController.findByRole": "start fetching by role (staff users)",
  "UserController.findOne": "start fetching one of staff users",
  "UserController.remove": "start deleting staff users",
  "UserController.resetPassword": "start reset password (staff users)",
  "UserController.search": "start searching staff users",
  "UserController.toggleActive": "start updating toggle active (staff users)",
  "UserController.update": "start updating staff users",
  "UserController.updatePassword": "start updating update password (staff users)",
  "WeeklySessionPlanController.completeSession": "start updating complete session (weekly session plans)",
  "WeeklySessionPlanController.copyFromPreviousWeek": "start copy from previous week (weekly session plans)",
  "WeeklySessionPlanController.createWeeklySessionPlan": "start creating weekly session plans",
  "WeeklySessionPlanController.deleteWeeklySessionPlan": "start deleting delete weekly session plan (weekly session plans)",
  "WeeklySessionPlanController.getGroupWeeklyPlanning": "start fetching group weekly planning (weekly session plans)",
  "WeeklySessionPlanController.getWeeklySessionPlanById": "start fetching weekly session plan by id (weekly session plans)",
  "WeeklySessionPlanController.getWeeklySessionPlans": "start fetching weekly session plans (weekly session plans)",
  "WeeklySessionPlanController.markSessionComplete": "start updating mark session complete (weekly session plans)",
  "WeeklySessionPlanController.markSessionIncomplete": "start updating mark session incomplete (weekly session plans)",
  "WeeklySessionPlanController.updateSessionStatus": "start updating update session status (weekly session plans)",
  "WeeklySessionPlanController.updateTaskStatus": "start updating update task status (weekly session plans)",
  "WeeklySessionPlanController.updateWeeklySessionPlan": "start updating update weekly session plan (weekly session plans)",
};

export function bizLogAction(controller: string, method: string, override?: string): string {
  if (override && override.trim()) return override.trim();
  return BIZ_LOG_CATALOG[`${controller}.${method}`] || `start ${method}`;
}

